apiVersion: v1
kind: ConfigMap
metadata:
  name: tavana-config
  namespace: tavana
data:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://minio:9000"
  S3_USE_PATH_STYLE: "true"
  WORKER_ADDR: "http://worker:50053"
