apiVersion: v1
kind: Service
metadata:
  name: tavana-gateway
  namespace: tavana
spec:
  type: NodePort
  selector:
    app: tavana-gateway
  ports:
    - port: 15432
      targetPort: 15432
      nodePort: 30432
      name: pgwire
    - port: 8815
      targetPort: 8815
      nodePort: 30815
      name: flight
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: tavana-worker
  namespace: tavana
spec:
  selector:
    app: tavana-worker
  ports:
    - port: 50053
      targetPort: 50053
      name: grpc

